version: 0.0.{build}-{branch}

branches:
  except:
    - gh-pages

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

image:
- Visual Studio 2017

install:
- sh: |
    sudo apt-get update
    sudo apt-get -yqq install python wget
    sudo apt-get -yqq install dh-autoreconf bison flex
    sudo apt-get -yqq install zlib1g-dev libglib2.0-dev libfdt-dev libpixman-1-dev libsdl2-dev libvulkan-dev libusb-1.0-0-dev
    wget http://archive.ubuntu.com/ubuntu/pool/universe/libz/libzip/libzip5_1.5.1-0ubuntu1_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/libz/libzip/libzip-dev_1.5.1-0ubuntu1_amd64.deb
    sudo dpkg -i libzip5_1.5.1-0ubuntu1_amd64.deb
    sudo dpkg -i libzip-dev_1.5.1-0ubuntu1_amd64.deb
    rm libzip5_1.5.1-0ubuntu1_amd64.deb
    rm libzip-dev_1.5.1-0ubuntu1_amd64.deb
- ps: |
    choco install -y windowsdriverkit10
    choco install -y windows-sdk-10.1
    PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
    PowerShell -File ci_msys_prepare.ps1 'C:\msys64'
    
before_build:
- git submodule update --init --recursive
- git submodule update --init --force

build_script:
- sh: ./build.sh
- ps: |
    PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
    PowerShell -File ci_msys_build.ps1 'C:\msys64'
    ./bin/qemu-system-ps4.exe